// Mocks generated by Mockito 5.4.4 from annotations
// in app_test/test/modules/auth/authentication/data/repositories/auth_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:app_test/modules/auth/authentication/data/datasources/auth_datasource.dart'
    as _i3;
import 'package:app_test/modules/auth/authentication/data/models/auth_model.dart'
    as _i5;
import 'package:app_test/modules/auth/authentication/data/models/result_auth_model.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeResultAuthModel_0 extends _i1.SmartFake
    implements _i2.ResultAuthModel {
  _FakeResultAuthModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AuthDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthDatasource extends _i1.Mock implements _i3.AuthDatasource {
  MockAuthDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.ResultAuthModel> auth(_i5.AuthModel? authModel) =>
      (super.noSuchMethod(
        Invocation.method(
          #auth,
          [authModel],
        ),
        returnValue:
            _i4.Future<_i2.ResultAuthModel>.value(_FakeResultAuthModel_0(
          this,
          Invocation.method(
            #auth,
            [authModel],
          ),
        )),
      ) as _i4.Future<_i2.ResultAuthModel>);
}
